# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazydockerNg < Formula
  desc "A simple terminal UI for docker, written in Go"
  homepage "https://github.com/peauc/lazydocker-ng/"
  version "0.25.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peauc/lazydocker-ng/releases/download/v0.25.0/lazydocker-ng_0.25.0_Darwin_x86_64.tar.gz"
      sha256 "48c0edb3ca3691447dfcdf7971783f42e880afa81ffdcf4b597cf2ca4dc8ccde"

      def install
        bin.install "lazydocker-ng"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peauc/lazydocker-ng/releases/download/v0.25.0/lazydocker-ng_0.25.0_Darwin_arm64.tar.gz"
      sha256 "7b2e91df3b1361a54889a74122ed075b4445c89203cacc467d9aca514db1b92f"

      def install
        bin.install "lazydocker-ng"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peauc/lazydocker-ng/releases/download/v0.25.0/lazydocker-ng_0.25.0_Linux_x86_64.tar.gz"
      sha256 "8ce2c14f5476f46f2064bc876e8c8b47175ec910318f032442e20d465c22c317"
      def install
        bin.install "lazydocker-ng"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peauc/lazydocker-ng/releases/download/v0.25.0/lazydocker-ng_0.25.0_Linux_armv6.tar.gz"
      sha256 "306d8fa0b7b623389cfe6c5dc6318282d9d0e5c74e24feb7aad2c79f02c3aa43"
      def install
        bin.install "lazydocker-ng"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peauc/lazydocker-ng/releases/download/v0.25.0/lazydocker-ng_0.25.0_Linux_arm64.tar.gz"
      sha256 "d2fda65be8841b2a59734700824baec1b3654d73737472fbe85c790b47b87106"
      def install
        bin.install "lazydocker-ng"
      end
    end
  end
end
