# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazydocker-ng" do
  name "lazydocker-ng"
  desc "The continuation of lazydocker the simple terminal UI for docker, written in Go"
  homepage "https://github.com/peauc/lazydocker-ng/"
  version "0.28.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazydocker-ng"

  on_macos do
    on_intel do
      url "https://github.com/peauc/lazydocker-ng/releases/download/v#{version}/lazydocker-ng_#{version}_Darwin_x86_64.tar.gz"
      sha256 "f0b94b2960ed1381c671bdc5890576301cfe1424de556354e69cb68e76db3899"
    end
    on_arm do
      url "https://github.com/peauc/lazydocker-ng/releases/download/v#{version}/lazydocker-ng_#{version}_Darwin_arm64.tar.gz"
      sha256 "f4e360e47d5ac679918064aa92d189e38aca618b3ba1f66510b9cab3a06192d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/peauc/lazydocker-ng/releases/download/v#{version}/lazydocker-ng_#{version}_Linux_x86_64.tar.gz"
      sha256 "66f6968c1a1730f8f49d4a797357fb0210a6736b04aa25fd56e12a8af562409b"
    end
    on_arm do
      url "https://github.com/peauc/lazydocker-ng/releases/download/v#{version}/lazydocker-ng_#{version}_Linux_arm64.tar.gz"
      sha256 "091d93b3009cfd8454e592fe5424a1f50941b61dcce74ab9b59444d095a579a5"
    end
  end

  # No zap stanza required
end
